### ISSUE TITLE
hcp-eks-demo module runs unsupported version of EKS (v1.21)

### ISSUE THREAD

**Issue by crhino** [hashicorp/terraform-aws-hcp-consul#86]
v1.21 was removed from EKS in Feb 15 (https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar)

Updating to v1.24 results in Hashicups failing to load. HashiCups might be failing to query between public-api -> product-api:
```
{"errors":[{"message":"Get http://product-api:9090/coffees: EOF","path":["coffees"]}],"data":null}
```

**Comment by riddhi89** [comment]
Fixed in https://github.com/hashicorp/terraform-aws-hcp-consul/pull/89
https://github.com/hashicorp/terraform-aws-hcp-consul/pull/87
